name:                halg-core-test
version:             0.1.0.0
github:              "konn/halg-core-test"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro _at_ gmail.com"
copyright:           "2018 (c) Hiromi ISHII"

extra-source-files:
- README.md
- ChangeLog.md

tested-with: |
  GHC == 8.4.3, GHC == 8.6.5, GHC == 8.8.2, GHC == 8.10.1

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/konn/halg-core-test#readme>

dependencies:
- algebraic-prelude
- base >= 4.7 && < 5
- singletons-presburger
- singletons
- equational-reasoning
- containers
- halg-core
- QuickCheck
- quickcheck-instances
- reflection
- sized
- smallcheck
- type-natural

library:
  source-dirs: src
  ghc-options:  -Wall -Wno-orphans
